# Generated by Django 2.2.5 on 2019-09-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='description',
            field=models.CharField(default=1, max_length=100, verbose_name='Desc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='slug',
            field=models.SlugField(default='qwe', unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
