# Generated by Django 2.2.5 on 2019-09-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190918_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='description',
            field=models.TextField(max_length=800, verbose_name='Desc'),
        ),
    ]
