# Generated by Django 2.2.5 on 2019-09-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190919_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='theme',
            field=models.CharField(choices=[('It', 'Работка'), ('Projects', 'Мои проекты'), ('Travel', 'Путешествия'), ('Mind', 'Мысли о всяком')], max_length=10),
        ),
    ]
