# Generated by Django 2.2.5 on 2019-09-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190919_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='theme',
            field=models.CharField(choices=[('1', 'Работка'), ('2', 'Мои проекты'), ('3', 'Путешествия'), ('4', 'Мысли о всяком')], max_length=1),
        ),
    ]
