# Generated by Django 2.2.5 on 2019-09-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190919_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='theme',
            field=models.CharField(choices=[('work', 'Работка'), ('my_projects', 'Мои проекты'), ('travels', 'Путешествия'), ('mind', 'Мысли о всяком')], max_length=10),
        ),
    ]
