# Generated by Django 2.2.2 on 2019-06-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('date_start_course', models.DateField(blank=True)),
                ('course_lenght', models.CharField(max_length=20)),
                ('teachers', models.ManyToManyField(to='teacher.Teacher')),
            ],
        ),
    ]
