# Generated by Django 2.2.2 on 2019-06-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(blank=True, default=22),
            preserve_default=False,
        ),
    ]
