# Generated by Django 2.2.2 on 2019-06-21 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
