# Generated by Django 2.2.2 on 2019-06-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_date_end_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_lenght',
        ),
    ]
