# Generated by Django 2.2.2 on 2019-06-21 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0001_initial'),
        ('course', '0007_auto_20190622_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='studients',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='profile_user.Profile'),
            preserve_default=False,
        ),
    ]
