# Generated by Django 2.2.2 on 2019-06-23 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0008_course_studients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='studients',
        ),
        migrations.AddField(
            model_name='course',
            name='studients',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
