# Generated by Django 2.2.2 on 2019-06-23 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20190623_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='studients',
            field=models.ManyToManyField(blank=True, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
