# Generated by Django 2.2.2 on 2019-06-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20190623_2345'),
        ('profile_user', '0002_auto_20190623_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(blank=True, to='course.Course'),
        ),
    ]
