# Generated by Django 2.2.2 on 2019-07-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_auto_20190624_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'get_latest_by': 'lesson_date', 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
    ]
