# Generated by Django 2.2.2 on 2019-06-21 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20190621_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподователь', 'verbose_name_plural': 'Преподователи'},
        ),
    ]
